services:
  - type: web
    name: school-frontend
    env: node
    buildCommand: npm install && npx --yes vite build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0